name: CI Pipeline

# Trigger on push or pull request to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Matches your dependency requirements
          cache: 'npm' # Caches based on package-lock.json

      # Step 3: Install dependencies using package-lock.json
      - name: Install dependencies
        run: npm ci # Uses package-lock.json for exact versions

      # Step 4: Run linting (if configured, won’t fail if absent)
      - name: Run lint
        run: npm run lint --if-present

      # Step 5: Run tests (placeholder, won’t fail if absent)
      - name: Run tests
        run: npm test --if-present || true

      # Step 6: Check for security vulnerabilities
      - name: Run security audit
        run: npm audit --audit-level=moderate # Fails on moderate or higher issues
